import crypto from 'crypto';
import { NextResponse } from 'next/server';
import { S3Client, PutObjectCommand } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
export const dynamic='force-dynamic'; export const runtime='nodejs';
const MAX=500*1024*1024; const BUCKET='edit-ia-media'; const VERSION='5.2.13';
const e=(n:string)=>process.env[n]?.trim().replace(/^['\"]|['\"]$/g,'')||'';
function storage(){const miss=['STORAGE_ENDPOINT','STORAGE_ACCESS_KEY','STORAGE_SECRET_KEY'].filter(n=>!e(n));if(miss.length)throw new Error(`Storage runtime configuration is missing: ${miss.join(', ')}`);const ep0=e('STORAGE_ENDPOINT'),ep=/^https?:\/\//i.test(ep0)?ep0:`https://${ep0}`;return{client:new S3Client({region:e('STORAGE_REGION')||'auto',endpoint:ep,forcePathStyle:true,credentials:{accessKeyId:e('STORAGE_ACCESS_KEY'),secretAccessKey:e('STORAGE_SECRET_KEY')}})};}
export async function POST(req:Request){try{const b=await req.json(),name=String(b?.name||'video.mp4'),size=Number(b?.size||0),type=String(b?.type||'video/mp4');if(!Number.isSafeInteger(size)||size<=0||size>MAX)return NextResponse.json({error:'Cada vídeo deve ter no máximo 500 MB.',version:VERSION},{status:413});if(type!=='video/mp4'&&!name.toLowerCase().endsWith('.mp4'))return NextResponse.json({error:'Somente arquivos MP4 são aceitos.',version:VERSION},{status:400});const{client}=storage(),safe=name.replace(/[^a-zA-Z0-9._-]/g,'_').slice(-120)||'video.mp4',key=`uploads/${crypto.randomUUID()}-${safe}`,url=await getSignedUrl(client,new PutObjectCommand({Bucket:BUCKET,Key:key,ContentType:'video/mp4'}),{expiresIn:900});return NextResponse.json({key,url,bucket:BUCKET,version:VERSION},{headers:{'Cache-Control':'no-store'}});}catch(x){return NextResponse.json({error:x instanceof Error?x.message:'Upload setup failed',version:VERSION},{status:500,headers:{'Cache-Control':'no-store'}})}}
