'use client';

import { useEffect, useRef, useState } from 'react';
import { characters } from '../data/characters';
import { editStyles } from '../data/styles';
import { playUiSound, setSoundEnabled } from '../lib/soundManager';

const MAX = 500 * 1024 * 1024;
const JOB_KEY = 'editia:last-job-id';
type Step = 'home'|'character'|'style'|'clips'|'confirm'|'processing'|'result';
type Clip = { file: File; url: string };
type Job = { id:string; status:string; stage?:string|null; progress?:number|null; detail?:string|null; output?:string|null; error?:string|null };
const stageText: Record<string,string> = { QUEUED:'Esperando al worker...', STARTING:'Iniciando worker...', DOWNLOADING:'Recibiendo vídeos...', ANALYZING:'Analizando referencia y fuente...', EDITING:'Reconstruyendo el estilo...', RENDER:'Renderizando tu vídeo...', RENDERING:'Renderizando tu vídeo...', QC:'Comprobando calidad...', CORRECTING:'Aplicando correcciones...', AUTOCORRECT:'Aplicando correcciones...', COMPLETED:'¡Tu edit está listo!' };
const flow: Step[] = ['character','style','clips','confirm','result'];

function valid(f:File|null){ return !!f && f.type==='video/mp4' && f.name.toLowerCase().endsWith('.mp4') && f.size>0 && f.size<=MAX; }
function size(n:number){ return `${(n/1024/1024).toFixed(n>=10*1024*1024?0:1)} MB`; }
function buzz(v:number|number[]=12){ try{ navigator.vibrate?.(v); }catch{} }
function isAbortError(value:unknown){ return value instanceof DOMException && value.name==='AbortError'; }

export default function Page(){
 const [step,setStep]=useState<Step>('home');
 const [characterId,setCharacterId]=useState('goku'); const [styleId,setStyleId]=useState('amv');
 const [reference,setReference]=useState<Clip|null>(null); const [source,setSource]=useState<Clip|null>(null);
 const [job,setJob]=useState<Job|null>(null); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [upload,setUpload]=useState(0); const [sound,setSound]=useState(true);
 const abortRef=useRef<AbortController|null>(null);
 const character=characters.find(c=>c.id===characterId) || characters[0]; const style=editStyles.find(s=>s.id===styleId) || editStyles[0];

 useEffect(()=>{ let active=true; try{ const p=JSON.parse(localStorage.getItem('editia:preferences')||'{}'); if(characters.some(c=>c.id===p.characterId))setCharacterId(p.characterId); if(editStyles.some(s=>s.id===p.styleId))setStyleId(p.styleId); const id=localStorage.getItem(JOB_KEY); if(id){setStep('processing');setBusy(true);poll(id).catch(e=>{if(active&&!isAbortError(e)){setError(e instanceof globalThis.Error?e.message:'No se pudo recuperar el trabajo.');setStep('confirm');}}).finally(()=>{if(active)setBusy(false);});} }catch{} return()=>{active=false;abortRef.current?.abort();}; },[]);
 useEffect(()=>{ try{localStorage.setItem('editia:preferences',JSON.stringify({characterId,styleId}));}catch{} },[characterId,styleId]);
 useEffect(()=>()=>{if(reference)URL.revokeObjectURL(reference.url);if(source)URL.revokeObjectURL(source.url);},[reference,source]);

 async function poll(id:string){ let errors=0; for(;;){ const controller=new AbortController(); const timer=setTimeout(()=>controller.abort(),12000); let r:Response; try{r=await fetch(`/api/jobs/${encodeURIComponent(id)}`,{cache:'no-store',signal:controller.signal});}finally{clearTimeout(timer);} if(r.status===404)throw new globalThis.Error('El trabajo ya no existe.'); if(!r.ok){errors++;if(errors>=3)throw new globalThis.Error('No se pudo consultar el estado del trabajo.');await new Promise(x=>setTimeout(x,4000));continue;} errors=0; const d=await r.json() as Job; setJob(d); if(d.status==='COMPLETED'){localStorage.removeItem(JOB_KEY);playUiSound('done');setStep('result');return;} if(d.status==='FAILED'||d.status==='CANCELED'){localStorage.removeItem(JOB_KEY);throw new globalThis.Error(d.error||'El procesamiento no pudo completarse.');} await new Promise(x=>setTimeout(x,3000)); } }

 function pick(kind:'reference'|'source',f:File|null){ if(!f)return; if(f.type!=='video/mp4'||!f.name.toLowerCase().endsWith('.mp4')){setError('Solo se aceptan archivos MP4.');return;} if(f.size>MAX){setError('Cada vídeo debe tener un máximo de 500 MB.');return;} setError(''); const c={file:f,url:URL.createObjectURL(f)}; if(kind==='reference'){if(reference)URL.revokeObjectURL(reference.url);setReference(c);}else{if(source)URL.revokeObjectURL(source.url);setSource(c);} buzz(); playUiSound('select'); }
 function remove(kind:'reference'|'source'){ if(kind==='reference'){if(reference)URL.revokeObjectURL(reference.url);setReference(null);}else{if(source)URL.revokeObjectURL(source.url);setSource(null);} }

 async function uploadFile(file:File,offset:number){ const prep=await fetch('/api/upload',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:file.name,size:file.size,type:file.type})}); const d=await prep.json().catch(()=>({})); if(!prep.ok)throw new globalThis.Error(d.error||`Error de subida (${prep.status}).`); if(!d.url||!d.key)throw new globalThis.Error('El servidor no devolvió una URL de subida válida.'); await new Promise<void>((resolve,reject)=>{const x=new XMLHttpRequest();x.open('PUT',d.url);x.setRequestHeader('content-type','video/mp4');x.upload.onprogress=e=>{if(e.lengthComputable)setUpload(offset+Math.round(e.loaded/e.total*50));};x.onload=()=>x.status>=200&&x.status<300?resolve():reject(new globalThis.Error(`Falló la subida (${x.status}).`));x.onerror=()=>reject(new globalThis.Error('Falló la conexión durante la subida.'));x.onabort=()=>reject(new DOMException('cancelado','AbortError'));x.send(file);});return d.key as string; }
 async function createJob(){ if(busy||!reference||!source||!valid(reference.file)||!valid(source.file)){setError('Falta seleccionar dos MP4 válidos.');return;} if(!navigator.onLine){setError('No hay conexión a internet.');return;} setBusy(true);setError('');setUpload(0);abortRef.current=new AbortController();buzz([15,35,15]);playUiSound('create');try{const a=await uploadFile(reference.file,0);const b=await uploadFile(source.file,50);const r=await fetch('/api/jobs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({reference:a,source:b,referenceSize:reference.file.size,sourceSize:source.file.size,characterId,styleId})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.id)throw new globalThis.Error(d.error||`No se pudo crear el trabajo (${r.status}).`);localStorage.setItem(JOB_KEY,d.id);setJob(d);setUpload(0);setStep('processing');await poll(d.id);}catch(e){if(!isAbortError(e)){setError(e instanceof globalThis.Error?e.message:'Error inesperado.');setStep('confirm');}}finally{abortRef.current=null;setBusy(false);} }

 const progress=typeof job?.progress==='number'?Math.max(0,Math.min(100,job.progress)):null; const ready=valid(reference?.file||null)&&valid(source?.file||null);
 return <main className="app" style={{'--accent':character.accent} as React.CSSProperties}><div className="particles" aria-hidden="true">{Array.from({length:16},(_,i)=><i key={i}/>)}</div><header className="topbar"><button className="brand" onClick={()=>step!=='processing'&&setStep('home')}><b>✦</b> EDIT-IA</button><button className="iconBtn" aria-label="Activar o desactivar sonido" onClick={()=>{const n=!sound;setSound(n);setSoundEnabled(n)}}>{sound?'♪':'×'}</button></header>
 {step!=='home'&&step!=='processing'&&step!=='result'&&<nav className="steps" aria-label="Pasos">{['PERSONAJE','ESTILO','CLIPS','CREAR','RESULTADO'].map((x,i)=><div key={x} className={`step ${i<=flow.indexOf(step)?'on':''}`}><b>{i+1}</b><span>{x}</span></div>)}</nav>}
 <section className="viewport">
 {step==='home'&&<div className="hero"><div className="powerOrb"><span>✦</span></div><p className="kicker">AI VIDEO EXPERIENCE</p><h1>EDIT-IA</h1><h2>CREATE YOUR EDIT</h2><p>Una interfaz móvil premium conectada al motor EDIT-IA. El teléfono selecciona y sube; el worker procesa.</p><button className="primary heroButton" onClick={()=>{buzz();playUiSound('confirm');setStep('character')}}>ENTER <span>→</span></button><small>MOBILE-FIRST · SERVER-SIDE PROCESSING</small></div>}
 {step==='character'&&<div className="panel"><Title eyebrow="01 · CHARACTER" title="¿QUÉ PERSONAJE QUIERES?" text="Los personajes son datos configurables y sus assets pueden sustituirse."/><div className="characterGrid">{characters.filter(c=>c.enabled).map(c=><button key={c.id} className={`characterCard ${characterId===c.id?'selected':''}`} style={{'--card-accent':c.accent} as React.CSSProperties} onClick={()=>{setCharacterId(c.id);buzz();playUiSound('select');setTimeout(()=>setStep('style'),180)}}><span className="portrait">{c.initials}</span><strong>{c.name}</strong><small>AURA · {c.aura}</small>{characterId===c.id&&<em>✓ SELECCIONADO</em>}</button>)}</div></div>}
 {step==='style'&&<div className="panel"><Title eyebrow="02 · STYLE" title="¿QUÉ TIPO DE EDIT?" text="Cada estilo admite referenceKey y thumbnailKey para conectar referencias reales de R2."/><div className="styleGrid">{editStyles.filter(s=>s.enabled).map(s=><button key={s.id} className={`styleCard ${styleId===s.id?'selected':''}`} onClick={()=>{setStyleId(s.id);buzz();playUiSound('select');setTimeout(()=>setStep('clips'),180)}}><div className="styleVisual" style={{background:`radial-gradient(circle at 70% 25%,${s.accent}88,transparent 35%),linear-gradient(145deg,#0c101b,${s.accent}22)`}}><span>{s.icon}</span></div><div><strong>{s.name}</strong><p>{s.description}</p><small>{s.duration} · {s.features.join(' · ')}</small></div>{styleId===s.id&&<em>✓ ESTILO SELECCIONADO</em>}</button>)}</div><button className="back" onClick={()=>setStep('character')}>← VOLVER</button></div>}
 {step==='clips'&&<div className="panel"><Title eyebrow="03 · CLIPS" title="PREPARA TUS CLIPS" text="MP4 solamente. Los vídeos no se renderizan en el navegador."/><div className="uploadGrid"><Upload title="VIDEO A · REFERENCIA" clip={reference} onPick={f=>pick('reference',f)} onRemove={()=>remove('reference')}/><Upload title="VIDEO B · FUENTE" clip={source} onPick={f=>pick('source',f)} onRemove={()=>remove('source')}/></div>{error&&<ErrorBox text={error}/>}<div className="actions"><button className="back" onClick={()=>setStep('style')}>← VOLVER</button><button className="primary" disabled={!ready} onClick={()=>setStep('confirm')}>CONTINUAR →</button></div></div>}
 {step==='confirm'&&<div className="panel"><Title eyebrow="04 · READY" title="TODO LISTO" text="El servidor generará el jobId. El worker existente realizará el procesamiento."/><div className="summary"><Row a="PERSONAJE" b={character.name}/><Row a="ESTILO" b={style.name}/><Row a="REFERENCIA" b={reference?.file.name||'—'}/><Row a="FUENTE" b={source?.file.name||'—'}/></div>{error&&<ErrorBox text={error}/>} {busy&&<div className="uploadState"><div><span>SUBIENDO VÍDEOS</span><b>{upload}%</b></div><i><u style={{width:`${upload}%`}}/></i></div>}<button className="createButton" disabled={!ready||busy} onClick={createJob}>⚡ {busy?'PREPARANDO...':'CREAR EDIT'}</button><button className="back" disabled={busy} onClick={()=>setStep('clips')}>← VOLVER</button><small className="security">🔒 R2/GitHub/worker secrets nunca se envían al cliente.</small></div>}
 {step==='processing'&&<div className="processing"><div className="powerOrb spinning"><span>✦</span></div><p className="kicker">{character.name} · {style.name}</p><h2>CREANDO TU EDIT</h2><p className="live" aria-live="polite">{job?.detail||stageText[job?.stage||'']||stageText[job?.status||'']||'Esperando al worker...'}</p>{progress!==null&&<div className="serverProgress"><div><span>PROGRESO REAL DEL SERVIDOR</span><b>{progress}%</b></div><i><u style={{width:`${progress}%`}}/></i></div>}<div className="timeline"><Stage text="Trabajo creado" done={!!job}/><Stage text="Worker conectado" done={['RUNNING','ANALYZING','EDITING','RENDERING','QC','CORRECTING','COMPLETED'].includes(job?.status||'')}/><Stage text="Analizando / reconstruyendo" done={['EDITING','RENDERING','QC','CORRECTING','COMPLETED'].includes(job?.status||'')}/><Stage text="Renderizando" done={['QC','CORRECTING','COMPLETED'].includes(job?.status||'')}/><Stage text="Control de calidad" done={job?.status==='COMPLETED'}/></div>{error&&<ErrorBox text={error}/>}<button className="ghost" onClick={()=>setStep('home')}>CERRAR · EL JOB CONTINÚA</button></div>}
 {step==='result'&&<div className="result"><div className="successOrb">✓</div><p className="kicker">PROCESS COMPLETE</p><h2>🔥 EDIT COMPLETADO</h2>{job?.output?<video className="resultVideo" controls playsInline preload="metadata" src={job.output}/>:<ErrorBox text="El servidor terminó pero no devolvió una URL de salida."/>}<div className="resultActions">{job?.output&&<><a className="primary" href={job.output} target="_blank" rel="noreferrer">▶ REPRODUCIR</a><a className="primary" href={job.output} download="editia-final.mp4">↓ GUARDAR MP4</a></>}<button className="ghost" onClick={()=>{localStorage.removeItem(JOB_KEY);setJob(null);setError('');setStep('character')}}>↻ CREAR OTRO EDIT</button></div></div>}
 </section></main>;
}
function Title({eyebrow,title,text}:{eyebrow:string;title:string;text:string}){return <div className="titleBlock"><p className="kicker">{eyebrow}</p><h2>{title}</h2><p>{text}</p></div>}
function Row({a,b}:{a:string;b:string}){return <div><span>{a}</span><strong>{b}</strong></div>}
function ErrorBox({text}:{text:string}){return <div className="error" role="alert">{text}</div>}
function Stage({text,done}:{text:string;done:boolean}){return <div className={`stage ${done?'done':''}`}><b>{done?'✓':'→'}</b><span>{text}</span></div>}
function Upload({title,clip,onPick,onRemove}:{title:string;clip:Clip|null;onPick:(f:File|null)=>void;onRemove:()=>void}){return <div className="uploadCard"><p>{title}</p>{clip?<div className="fileCard"><video src={clip.url} muted playsInline preload="metadata"/><div><strong>{clip.file.name}</strong><small>{size(clip.file.size)}</small></div><button onClick={onRemove} aria-label="Eliminar archivo">×</button></div>:<label className="dropZone"><span>＋</span><strong>SELECCIONAR MP4</strong><small>Galería · cámara · archivos</small><input type="file" accept="video/mp4,.mp4" onChange={e=>onPick(e.target.files?.[0]||null)}/></label>}</div>}
